### ISSUE TITLE
Need to manually join CORDEX user group before executing esgf.ipynb

### ISSUE THREAD

**Issue by jwohland** [larsbuntemeyer/notebooks#4]
Executing esgf.ipynb requires to
(a) create an account at ESGF
(b) manually join the CORDEX user group (e.g., by copying the URL given in the notebook into a browser)

Without (b), downloads cause cryptic error messages

```
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR context: (...)
```

**Comment by larsbuntemeyer** [comment]
Yes, i don't understand why the CORDEX access is still restricted (makes everything complicated). The license is more or less non-restrictive, so the data could just be made openly accessible (like CMIP5/6). Maybe we will know more after the Euro-Cordex GA next week (although that's only EURO-CORDEX). Accessing CORDEX datasets is a pain in general... see my suggestions here: https://github.com/euro-cordex/py-cordex/issues/39
