### ISSUE TITLE
create warning when ROI < 9 grid cells

### ISSUE THREAD

**Issue by christinenam** [larsbuntemeyer/notebooks#6]
A warning must be issued for any Region of Interest (ROI) that is less than 9 model grid boxes. This may occur on the landkreise scale example. There is a 'hard' limit that all ROI must include 4 model grid boxes, even if it covers only 1 model grid box.

I wrote a solution below input 26:
https://gitlab.hzdr.de/gerics/data-processing/create-cvs-from-time-series/-/blob/main/EUR11_cordex-ensemble_tas.csv.completed.ipynb

**Comment by larsbuntemeyer** [comment]
moved to: https://gitlab.hzdr.de/gerics/data-processing/climate-fact-data/-/issues/2

**Comment by ludwiglierhammer** [comment]
I closed the issue in xweights. The number of grid points per region of interest will be written as extra column to the output pd.dataframe.
